### ISSUE TITLE
regex != pattern

### ISSUE THREAD

**Issue by joereynolds** [stein197/lua-string#3]
Throughout the readme, comments and code itself the term 'regex' is used.
This is misleading, lua patterns aren't regular expressions so you probably shouldn't hint to the users that they are.

They should probably be renamed to 'pattern' where appropriate

**Comment by stein197** [comment]
Replaced "regex" with "pattern" where possible (see commit b3746338c69c8fee1ae45ae9a3984a6b1258f79f). `string.*regex*()` methods are deprecated. But as far as I know, strictly saying, Lua patterns are regular expressions too
