### ISSUE TITLE
Type mismatch in function mt:__mul(n)

### ISSUE THREAD

**Issue by yaSebastian** [stein197/lua-string#5]
When looking through the code, Lua Diagnostics states the following type mismatch on the following line of code in `function mt:__mul(n)`:

> Annotations specify that return value # 1 has a type of `string`, returning value of type `number` here instead.
> - `number` cannot match `string`
> - Type `number` cannot match `string`

```lua
return n * self
```

---

Also, I'm still quite inexperienced in Lua, so please have my apologies if this is a really stupid question, but in the following code, shouldn't it be impossible for self to be a `number`? As far as I understand, `__mul(n)` would always be called on a string, unless someone applies either the metatable to another table or the function to another metatable, in which cases you'd have to check against a plethora of other conditions as well.

```lua
if type(self) == "number" then
	return n * self
end
```

**Comment by stein197** [comment]
It's an old code and it will be hard to recall. As far as I remember, you can call `"string" * 5` as well as `5 * "string"`. In the second example `self` would be equal to number because of the operands order. But now I look at the code and I wonder what made me to do this
